version: "3"
services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./nginx-basic-auth/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-basic-auth/htpasswd:/etc/nginx/htpasswd
    ports:
      - 8000:80
    depends_on:
      - app
