# Generated by Django 2.2.1 on 2019-06-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("curation_portal", "0001_initial")]

    operations = [
        migrations.AlterField(model_name="variant", name="xpos", field=models.BigIntegerField())
    ]
