# Generated by Django 2.2.4 on 2019-10-30 18:14

from django.db import migrations


def remove_blank_verdicts(apps, schema_editor):  # pylint: disable=unused-argument
    CurationResult = apps.get_model(  # pylint: disable=invalid-name
        "curation_portal", "CurationResult"
    )
    for result in CurationResult.objects.filter(verdict="").all():
        result.verdict = None
        result.save()


class Migration(migrations.Migration):

    dependencies = [("curation_portal", "0003_add_variant_tags")]

    operations = [migrations.RunPython(remove_blank_verdicts)]
