# Generated by Django 2.2.4 on 2019-10-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("curation_portal", "0004_remove_blank_verdicts")]

    operations = [
        migrations.AlterField(
            model_name="curationresult",
            name="verdict",
            field=models.CharField(max_length=25, null=True, blank=False),
        )
    ]
