# Generated by Django 2.2.20 on 2021-04-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("curation_portal", "0006_usersettings")]

    operations = [migrations.DeleteModel(name="Sample")]
