# Generated by Django 2.2.20 on 2021-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("curation_portal", "0007_delete_sample")]

    operations = [
        migrations.AddField(
            model_name="curationresult",
            name="flag_ab_filter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curationresult",
            name="flag_first_150_bp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curationresult",
            name="flag_in_frame_exon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curationresult",
            name="flag_long_exon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curationresult",
            name="flag_possible_splice_site_rescue",
            field=models.BooleanField(default=False),
        ),
    ]
