# Generated by Django 2.2.22 on 2021-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("curation_portal", "0010_rename_ab_flag")]

    operations = [
        migrations.AddField(
            model_name="curationresult",
            name="flag_untranslated_transcript",
            field=models.BooleanField(default=False),
        )
    ]
